### ISSUE TITLE
Bug re: state management

### ISSUE THREAD

**Issue by curran** [earthrise-media/story-ukraine-grain#18]
I notice what seems like a bug related to state management.

On page load, I see this:

![Image](https://user-images.githubusercontent.com/68416/216658506-fdc1f98e-6fc7-4530-95ba-a220de6c8ed1.png)

When I switch to another button, then switch back again to the initially selected one, I see this:

![Image](https://user-images.githubusercontent.com/68416/216658641-778df2fe-d5a7-4165-9992-4e9a69348cbe.png)

**Comment by ejfox** [comment]
Probably because on load we use a default domain [0,1000] and when you switch back it actually calculates the scale with the extent https://github.com/earthrise-media/story-ukraine-grain/blob/eb6c2a1eb40d667f74e9dd2556bebb1c65a86af6/pages/map.vue#L224

**Comment by curran** [comment]
Nice catch! Looks like you know exactly how to solve this.
