### ISSUE TITLE
Import all source data to app

### ISSUE THREAD

**Issue by curran** [earthrise-media/story-ukraine-grain#4]
* [X] Ukraine GeoJSON
 * [X] CSVs from 2021 UKR
 * [ ] World Bank
 * [ ] USDA
 * [ ] ComTrade

**Comment by ejfox** [comment]
Right now we are pulling in UKRStat and GeoJSON of oblasts

We may add comtrade or USDA data later, so keeping this open

**Comment by ejfox** [comment]
Comtrade: https://observablehq.com/d/403c4f8e8e8b273f

USDA https://ipad.fas.usda.gov/countrysummary/Default.aspx?id=UP
World Bank https://data.worldbank.org/indicator/AG.PRD.CREL.MT?locations=UA
UKRStat https://ukrstat.gov.ua/, https://ukrstat.gov.ua/operativ/operativ2021/sg/ovuzpsg/Arh_ovuzpsg_2021_e.html https://ukrstat.gov.ua/operativ/menu/menu_e/cg.htm
https://ukrstat.gov.ua/operativ/operativ2021/sg/ovuzpsg/Arh_ovuzpsg_2021_e.html

Pull 2021 data from as many sources as have it for Ukraine
